# SwiftLint Configuration — swift-gherkin-generator
# Swift 6.2 strict concurrency library

# Paths to exclude
excluded:
  - .build
  - Tests/GherkinGeneratorTests/Resources

# Enabled rules (opt-in)
opt_in_rules:
  - force_unwrapping
  - force_cast
  - force_try
  - vertical_whitespace
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - todo

# Disabled rules
disabled_rules:
  - identifier_name
  - blanket_disable_command
  - trailing_whitespace

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2
  function_level: 3

vertical_whitespace:
  max_empty_lines: 2
