# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Atelier Socle SAS

name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: checkboxes
    id: search
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How you think this could be implemented.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered.
    validations:
      required: false
